name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run tests with MicroPython
      run: |
        docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace \
          micropython/unix:latest \
          micropython -m pytest tests/